-- CREATE TABLE Customers(
-- CustomerID UNIQUEIDENTIFIER PRIMARY KEY,
-- Email NVARCHAR(50) NOT NULL,
-- Password NVARCHAR(25) NOT NULL
-- );
-- CREATE TABLE Inventory(
-- ItemID INT PRIMARY KEY IDENTITY(1000,10),
-- ItemName NVARCHAR(25),
-- Quantity INT NOT NULL,
-- Price MONEY NOT NULL
-- );
-- CREATE TABLE Orders(
-- OrderID UNIQUEIDENTIFIER PRIMARY KEY,
-- CustomerID_FK UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Customers(CustomerID) NOT NULL,
-- RedBricks INT DEFAULT 0 NOT NULL,
-- BlueBricks INT DEFAULT 0 NOT NULL,
-- YellowBricks INT DEFAULT 0 NOT NULL );

CREATE TABLE Customers(
CustomerID INT PRIMARY KEY IDENTITY(1,1),
Email NVARCHAR(50) NOT NULL,
Password NVARCHAR(25) NOT NULL
);
CREATE TABLE Inventory(
ItemID INT PRIMARY KEY IDENTITY(1000,10),
ItemName NVARCHAR(25),
Quantity INT NOT NULL,
Price MONEY NOT NULL
);
CREATE TABLE Orders(
OrderID INT PRIMARY KEY IDENTITY(100,1),
CustomerID_FK INT FOREIGN KEY REFERENCES Customers(CustomerID) NOT NULL,
RedBricks INT DEFAULT 0 NOT NULL,
BlueBricks INT DEFAULT 0 NOT NULL,
YellowBricks INT DEFAULT 0 NOT NULL );